modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
    modId = "mudaemod"
    version = "1.4"
    displayName = "Mudae Mod"
    description = '''
Colecciona personajes de anime y manga en Minecraft.
Click derecho en la Terminal de Mudae para invocar waifus y husbandos!
'''

[[dependencies.mudaemod]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.mudaemod]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21.1,1.22)"
    ordering = "NONE"
    side = "BOTH"
