modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
    modId = "mudaemod"
    version = "1.0.0"
    displayName = "Mudae Mod"
    description = '''
Collect anime/manga characters powered by AniList API.
Use /w or /h to roll for waifus and husbandos!
'''

[[dependencies.mudaemod]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.mudaemod]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21.1,1.22)"
    ordering = "NONE"
    side = "BOTH"
